name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 5.6.40 # Change to the php version your application is using
        extensions: mbstring, bcmath # Install any required php extensions
    - name: Install Dependencies
      run: composer install
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit tests --testdox  